id: I47481045
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T16:40:45+00:00'
last_modified: '2022-06-08T03:44:26.949416+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6445
  title: སྐུ་གསུམ་སྒྲུབ་བརྒྱུད་པའི་བླ་རབས་ཀྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    6E9F:
      image_group_id: I3CN6447
      title: ''
      total_pages: 1076
      order: 1
      base_file: 6E9F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
