id: P005530
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:56:41.486497
source_metadata:
  id: bdr:W3CN6445
  title: སྐུ་གསུམ་སྒྲུབ་བརྒྱུད་པའི་བླ་རབས་ཀྱི་རྣམ་ཐར།
  author: ''
  volumes:
    d353fe008650432aacd0a9db6d132d49:
      image_group_id: I3CN6447
      title: ''
      volume_number: 1
      total_pages: 1076
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
